/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {

        if (args.length == 1){
            System.out.println("Hello "+ args[0]);
        } else {
            System.out.println("Hello World");

        }
    }
}
