/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo.app;

import ads.poo.list.LinkedList;

import static ads.poo.utilities.StringUtils.join;
import static ads.poo.utilities.StringUtils.split;
import static ads.poo.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
