/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Aluno a = new Aluno("Juca","123","Carlos","Carla");

        a.adicionarDisciplina("POO");
        a.adicionarDisciplina("FDM");
        a.adicionarTelefone("93834-9012");
        a.adicionarTelefone("02394-0923");
        System.out.println(a);





    }
}
