/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;
import org.checkerframework.checker.units.qual.C;

import java.awt.*;

public class App {

    private Draw draw;

    public App(){
        this.draw = new Draw();;
        this.draw.setCanvasSize(600,300);
        this.draw.setXscale(0,600);
        this.draw.setYscale(0,300);
    }

    public void quadrado(){

    }

    public static void main(String[] args) {
//        App app = new App();
//        app.draw.circle(300,150,30);
//        app.draw.square(300,150,50);
//        Color verde = new Color(50,160,65);
//        Color vermelho = new Color(200,25,30);
//        app.draw.setPenColor(verde);
//        app.draw.filledRoundRectangle(300,150,150,75,25,25);

        Circulo c = new Circulo(.5,.5,.1,Color.green);

        c.desenhar(new Draw());

        Grade g = new Grade(.2,.2,.1,5,5, Color.blue);
        g.desenhar(new Draw());

    }
}
