/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import ads.poo.exercicio1.*;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {

        ArrayList<Animal> animais = new ArrayList<>();

        animais.add(new Cachorro("Tobby"));
        animais.add(new Gato("Pluma"));
        animais.add(new Leão("Simba"));
        animais.add(new Arara("Blue"));
        animais.add(new Pinguim("Ta dando onda"));

        for (Animal animal : animais) {
            System.out.println(animal + " logo: " + animal.habilidade());
        }
    }
}
