/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {

        Ferrari n = new Ferrari(123);


    }
}
