/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo.utilities;

import ads.poo.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
